# Generated by Django 5.2.14 on 2026-05-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_companyservicecategory_companyservicesubcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority2_delay_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minutes before priority-2 technicians see a new order.",
                    ),
                ),
                (
                    "priority3_delay_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutes before priority-3 technicians see a new order.",
                    ),
                ),
                (
                    "show_future_orders_to_technicians",
                    models.BooleanField(
                        default=False,
                        help_text="If True, technicians can see orders scheduled in the future.",
                    ),
                ),
                (
                    "future_orders_visible_after",
                    models.TimeField(
                        blank=True,
                        help_text="Time of day after which future orders become visible (if enabled).",
                        null=True,
                    ),
                ),
                (
                    "max_active_orders_per_technician",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Max concurrent in-progress orders a technician can hold.",
                    ),
                ),
                (
                    "auto_recycle_cancel_request",
                    models.BooleanField(
                        default=False,
                        help_text="If True, cancelled orders are automatically recycled back to NEW.",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company Settings",
            },
        ),
    ]
