# Generated by Django 6.0.5 on 2026-05-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_companysettings_default_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='respect_sms_template_time_window',
            field=models.BooleanField(default=True, help_text='If True, SMS messages respect template send_start_time/send_end_time windows.'),
        ),
    ]
