# Generated by Django 5.2.14 on 2026-05-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("tenants", "0003_companysettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicianCategorySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Priority 1"),
                            (2, "Priority 2"),
                            (3, "Priority 3"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_skills",
                        to="tenants.companyservicecategory",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_skills",
                        to="accounts.technician",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("technician", "category"),
                        name="unique_technician_category_skill",
                    )
                ],
            },
        ),
    ]
