# Generated by Django 5.2.14 on 2026-05-27 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_techniciancategoryskill'),
        ('tenants', '0006_phase26_sms_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(max_length=180)),
                ('is_allowed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_permissions', to='tenants.company')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['operator_id', 'permission_key'],
                'constraints': [models.UniqueConstraint(fields=('company', 'operator', 'permission_key'), name='unique_operator_permission_per_company_operator_key')],
            },
        ),
    ]
