# Generated by Django 6.0.5 on 2026-05-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registration_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Primary login identifier. Lowercase, letters/numbers/underscore/dash.', max_length=50, null=True, unique=True),
        ),
    ]
