# Generated by Django 6.0.5 on 2026-05-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_make_username_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Mobile phone for OTP/contact. Not unique — same person may have multiple accounts.', max_length=15),
        ),
    ]
