# Generated by Django 6.0.5 on 2026-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique per company. Format: INV-<CODE>-<SEQUENCE>', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
