# Generated by Django 5.2.14 on 2026-05-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_techniciancategoryskill'),
        ('invoices', '0003_invoice_operational_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_public__7251b6_idx',
            old_name='invoices_in_public_08b0d2_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='accounts.customer'),
        ),
    ]
