# Generated by Django 5.2.14 on 2026-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_available', 'Order Available'), ('order_assigned', 'Order Assigned'), ('order_accepted', 'Order Accepted'), ('order_completed', 'Order Completed'), ('invoice_issued', 'Invoice Issued'), ('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed')], max_length=30),
        ),
    ]
