# Generated by Django 5.2.14 on 2026-05-27 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
        ('tenants', '0006_phase26_sms_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_available', 'Order Available'), ('order_assigned', 'Order Assigned'), ('order_accepted', 'Order Accepted'), ('order_completed', 'Order Completed'), ('order_cancel_requested', 'Order Cancel Requested'), ('order_cancel_approved', 'Order Cancel Approved'), ('order_cancel_rejected', 'Order Cancel Rejected'), ('invoice_issued', 'Invoice Issued'), ('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed')], max_length=30),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(choices=[('order_created_admin', 'سفارش جدید / درخواست سفارش'), ('order_available_technician', 'سفارش جدید برای تکنسین'), ('order_assigned_technician', 'تخصیص سفارش به تکنسین'), ('order_accepted_customer', 'تایید / پذیرش سفارش'), ('order_completed_customer', 'اتمام سفارش'), ('order_cancel_requested_admin', 'درخواست لغو سفارش'), ('order_cancel_approved_technician', 'تایید لغو سفارش'), ('order_cancel_rejected_technician', 'رد لغو سفارش'), ('invoice_issued_customer', 'صدور فاکتور'), ('payment_success_customer', 'پرداخت موفق'), ('payment_failed_customer', 'پرداخت ناموفق'), ('survey_request_customer', 'نظرسنجی')], max_length=60)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'ordering': ['event_key'],
                'constraints': [models.UniqueConstraint(fields=('company', 'event_key'), name='unique_notification_setting_per_company_event')],
            },
        ),
    ]
