# Generated by Django 6.0.5 on 2026-05-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0001_initial'),
        ('tenants', '0006_phase26_sms_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('PLATFORM_OWNER', 'مدیر پلتفرم'), ('COMPANY', 'شرکت'), ('COMPANY_ADMIN', 'مدیر شرکت'), ('TECHNICIAN', 'تکنسین'), ('CUSTOMER', 'مشتری'), ('CUSTOM', 'سفارشی')], default='COMPANY', max_length=20)),
                ('channel', models.CharField(choices=[('INTERNAL', 'داخلی'), ('SMS_FUTURE', 'پیامک (آینده)'), ('EMAIL_FUTURE', 'ایمیل (آینده)')], default='INTERNAL', max_length=20)),
                ('direction', models.CharField(choices=[('INBOUND', 'دریافتی'), ('OUTBOUND', 'ارسالی')], default='OUTBOUND', max_length=10)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('QUEUED', 'در صف ارسال'), ('SENT', 'ارسال شده'), ('FAILED', 'ناموفق'), ('READ', 'خوانده شده')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_messages', to='tenants.company')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_platform_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='Null if system-generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_platform_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Message',
                'verbose_name_plural': 'Platform Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
