# Generated by Django 6.0.5 on 2026-05-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0002_platform_message'),
        ('tenants', '0006_phase26_sms_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, help_text='Machine-readable event key (e.g. order_created_admin).', max_length=80)),
                ('channel', models.CharField(choices=[('SMS', 'پیامک'), ('EMAIL', 'ایمیل'), ('IN_APP', 'اعلان داخلی'), ('INTERNAL', 'پیام داخلی')], max_length=20)),
                ('recipient_type', models.CharField(choices=[('COMPANY_ADMIN', 'مدیر شرکت'), ('TECHNICIAN', 'تکنسین'), ('CUSTOMER', 'مشتری'), ('PLATFORM_OWNER', 'مدیر پلتفرم')], max_length=20)),
                ('title', models.CharField(help_text='Notification/message title.', max_length=300)),
                ('body', models.TextField(help_text='Template body. Supports {{ placeholders }}.')),
                ('action_label', models.CharField(blank=True, help_text="Button/link label (e.g. 'مشاهده سفارش').", max_length=100)),
                ('action_url_template', models.CharField(blank=True, help_text='URL template with placeholders (e.g. /{{ company_code }}/admin/orders/{{ order_id }}/).', max_length=300)),
                ('allowed_placeholders', models.TextField(blank=True, help_text='Comma-separated list of allowed placeholders.')),
                ('is_active', models.BooleanField(default=True, help_text='Globally active. If False, never used anywhere.')),
                ('is_required', models.BooleanField(default=False, help_text='If True, tenant companies cannot disable this template.')),
                ('allow_company_toggle', models.BooleanField(default=True, help_text='If True, tenant admins can enable/disable for their company.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Communication Template',
                'verbose_name_plural': 'Communication Templates',
                'ordering': ['event_key', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('event_key', 'channel', 'recipient_type'), name='unique_comm_template_event_channel_recipient')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplateCompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_settings', to='tenants.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='platform_core.communicationtemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Communication Setting',
                'verbose_name_plural': 'Company Communication Settings',
                'constraints': [models.UniqueConstraint(fields=('company', 'template'), name='unique_comm_setting_per_company_template')],
            },
        ),
    ]
