# Generated by Django 6.0.5 on 2026-05-28 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0002_platform_message'),
        ('tenants', '0006_phase26_sms_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySMSWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_rial', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_wallet', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Company SMS Wallet',
            },
        ),
        migrations.CreateModel(
            name='GlobalSMSPricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters_per_sms', models.PositiveIntegerField(default=60)),
                ('price_per_sms_rial', models.PositiveIntegerField(default=520)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Pricing Setting',
            },
        ),
        migrations.CreateModel(
            name='PlatformBillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('SMS_RECHARGE', 'شارژ پیامک'), ('SUBSCRIPTION', 'اشتراک'), ('MANUAL', 'دستی'), ('OTHER', 'سایر')], default='SMS_RECHARGE', max_length=20)),
                ('amount_rial', models.BigIntegerField()),
                ('status', models.CharField(choices=[('UNPAID', 'پرداخت نشده'), ('PAID', 'پرداخت شده'), ('CANCELED', 'لغو شده')], default='UNPAID', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_invoices', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_platform_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySMSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'شارژ'), ('DEBIT', 'مصرف'), ('ADJUSTMENT', 'تعدیل'), ('BLOCKED', 'مسدود (اعتبار ناکافی)')], max_length=15)),
                ('amount_rial', models.BigIntegerField()),
                ('sms_parts', models.PositiveIntegerField(default=0)),
                ('message_length', models.PositiveIntegerField(default=0)),
                ('balance_after', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_transactions', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='platform_core.companysmswallet')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_core.platformbillinginvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
