# Generated by Django 6.0.5 on 2026-05-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0003_sms_credit_wallet_billing'),
        ('tenants', '0006_phase26_sms_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rial', models.BigIntegerField()),
                ('provider', models.CharField(choices=[('MANUAL', 'پرداخت دستی'), ('ZARINPAL_FUTURE', 'زرین\u200cپال (آینده)'), ('IDPAY_FUTURE', 'آیدی\u200cپی (آینده)'), ('PAYPING_FUTURE', 'پی\u200cپینگ (آینده)'), ('OTHER_FUTURE', 'سایر (آینده)')], default='MANUAL', max_length=20)),
                ('authority', models.CharField(blank=True, help_text='Gateway authority/token', max_length=100)),
                ('tracking_code', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('INITIATED', 'آغاز شده'), ('REDIRECTED', 'هدایت به درگاه'), ('PAID', 'پرداخت شده'), ('FAILED', 'ناموفق'), ('CANCELED', 'لغو شده'), ('VERIFIED', 'تایید شده')], default='INITIATED', max_length=15)),
                ('gateway_response', models.TextField(blank=True, help_text='Raw gateway response JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_payment_transactions', to='tenants.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='platform_core.platformbillinginvoice')),
            ],
            options={
                'verbose_name': 'Platform Payment Transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
