# Generated by Django 6.0.5 on 2026-05-28 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0004_payment_transaction'),
        ('tenants', '0006_phase26_sms_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('COMPANY_REGISTERED', 'ثبت\u200cنام شرکت'), ('COMPANY_APPROVED', 'تأیید شرکت'), ('ORDER_CREATED', 'ایجاد سفارش'), ('ORDER_ASSIGNED', 'تخصیص سفارش'), ('ORDER_STATUS_CHANGED', 'تغییر وضعیت سفارش'), ('INVOICE_CREATED', 'صدور فاکتور'), ('PAYMENT_RECEIVED', 'دریافت پرداخت'), ('SMS_CREDIT_LOW', 'اعتبار پیامک کم'), ('SMS_CREDIT_EMPTY', 'اعتبار پیامک تمام'), ('TECHNICIAN_NOTIFICATION', 'اعلان تکنسین'), ('OPERATOR_NOTIFICATION', 'اعلان اپراتور')], max_length=40)),
                ('channel', models.CharField(choices=[('INTERNAL_NOTIFICATION', 'اعلان داخلی'), ('SMS', 'پیامک'), ('EMAIL_FUTURE', 'ایمیل (آینده)')], max_length=30)),
                ('recipient_type', models.CharField(choices=[('COMPANY_ADMIN', 'مدیر شرکت'), ('OPERATOR', 'اپراتور'), ('TECHNICIAN', 'تکنسین'), ('PLATFORM_OWNER', 'مدیر پلتفرم')], max_length=20)),
                ('title_template', models.CharField(max_length=300)),
                ('body_template', models.TextField()),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('action_url_template', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('allow_company_toggle', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null = global default. Set = company-specific override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_templates', to='tenants.company')),
            ],
            options={
                'verbose_name': 'Communication Template',
                'ordering': ['event_key', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplateCompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_template_settings', to='tenants.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='platform_core.communicationtemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'template'), name='unique_comm_tpl_setting_per_company')],
            },
        ),
    ]
