# Generated by Django 6.0.5 on 2026-05-28 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0005_communication_templates'),
        ('tenants', '0006_phase26_sms_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPaymentGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MOCK', 'آزمایشی (بدون اتصال)'), ('MANUAL', 'پرداخت دستی'), ('ZARINPAL_FUTURE', 'زرین\u200cپال (آینده)'), ('ZIBAL_FUTURE', 'زیبال (آینده)'), ('IDPAY_FUTURE', 'آیدی\u200cپی (آینده)'), ('PAYPING_FUTURE', 'پی\u200cپینگ (آینده)')], default='MOCK', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('merchant_id', models.CharField(blank=True, help_text='Merchant ID or API key (masked in UI)', max_length=200)),
                ('terminal_id', models.CharField(blank=True, max_length=100)),
                ('callback_base_url', models.CharField(blank=True, max_length=300)),
                ('sandbox_mode', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway', to='tenants.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Payment Gateway',
            },
        ),
        migrations.CreateModel(
            name='PlatformPaymentGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MOCK', 'آزمایشی (بدون اتصال)'), ('MANUAL', 'پرداخت دستی'), ('ZARINPAL_FUTURE', 'زرین\u200cپال (آینده)'), ('ZIBAL_FUTURE', 'زیبال (آینده)'), ('IDPAY_FUTURE', 'آیدی\u200cپی (آینده)'), ('PAYPING_FUTURE', 'پی\u200cپینگ (آینده)')], default='MOCK', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('merchant_id', models.CharField(blank=True, help_text='Merchant ID or API key (masked in UI)', max_length=200)),
                ('terminal_id', models.CharField(blank=True, max_length=100)),
                ('callback_base_url', models.CharField(blank=True, help_text='e.g. https://rastiservice.ir', max_length=300)),
                ('sandbox_mode', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Payment Gateway',
            },
        ),
    ]
