# Generated by Django 6.0.5 on 2026-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('price_estimate', models.DecimalField(decimal_places=0, default=0, help_text='Estimated price before work starts.', max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=0, default=0, help_text='Final price after work is done.', max_digits=12)),
                ('required_skill', models.CharField(blank=True, help_text='Required skill name for technician matching.', max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='Optional note about the change.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
