# Generated by Django 5.2.14 on 2026-05-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_note',
            field=models.TextField(blank=True, help_text='Admin/staff internal note. Not visible to customers.'),
        ),
    ]
