# Generated by Django 5.2.14 on 2026-05-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_internal_note'),
        ('tenants', '0002_companyservicecategory_companyservicesubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenants.companyservicecategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenants.companyservicesubcategory'),
        ),
    ]
