# Generated by Django 5.2.14 on 2026-05-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_service_category_order_service_subcategory"),
        ("tenants", "0003_companysettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when a technician accepted this order.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="priority2_visible_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this order becomes visible to priority-2 technicians.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="priority3_visible_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this order becomes visible to priority-3 technicians.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="OrderItemDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("money", "Money"),
                            ("text", "Text"),
                            ("bool", "Boolean"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_definitions",
                        to="tenants.companyservicecategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="OrderItemValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="orders.orderitemdefinition",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_values",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "item"), name="unique_order_item_value"
                    )
                ],
            },
        ),
    ]
