# Generated by Django 6.0.5 on 2026-05-26 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
        ('tenants', '0006_phase26_sms_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsoutbox',
            name='invoice_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='send_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled send time (for time-window logic).', null=True),
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='template_key',
            field=models.CharField(blank=True, choices=[('order_created_admin', 'سفارش جدید - مدیر'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'قبول سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر'), ('order_cancel_approved_technician', 'تایید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری')], max_length=50),
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'قبول سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر'), ('order_cancel_approved_technician', 'تایید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('template_text', models.TextField(help_text='Django template syntax. Variables: {{ order_id }}, {{ customer_name }}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('send_start_time', models.TimeField(blank=True, help_text='Earliest time of day to send (e.g. 08:00).', null=True)),
                ('send_end_time', models.TimeField(blank=True, help_text='Latest time of day to send (e.g. 22:00).', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.company')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='smsoutbox',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_messages', to='sms.smstemplate'),
        ),
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_sms_template_per_company'),
        ),
    ]
