# Generated by Django 5.2.14 on 2026-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_phase26_sms_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsoutbox',
            name='template_key',
            field=models.CharField(blank=True, choices=[('order_created_admin', 'سفارش جدید - مدیر'), ('order_available_technician', 'سفارش جدید - تکنسین'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'قبول سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر'), ('order_cancel_approved_technician', 'تایید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='key',
            field=models.CharField(choices=[('order_created_admin', 'سفارش جدید - مدیر'), ('order_available_technician', 'سفارش جدید - تکنسین'), ('order_assigned_technician', 'تخصیص سفارش - تکنسین'), ('order_accepted_customer', 'قبول سفارش - مشتری'), ('order_completed_customer', 'اتمام سفارش - مشتری'), ('order_cancel_requested_admin', 'درخواست لغو - مدیر'), ('order_cancel_approved_technician', 'تایید لغو - تکنسین'), ('order_cancel_rejected_technician', 'رد لغو - تکنسین'), ('invoice_issued_customer', 'صدور فاکتور - مشتری'), ('payment_success_customer', 'پرداخت موفق - مشتری'), ('payment_failed_customer', 'پرداخت ناموفق - مشتری'), ('survey_request_customer', 'نظرسنجی - مشتری')], max_length=50),
        ),
    ]
